kafka:
  brokers:
    - kafka:9092

schemaRegistry:
  enabled: true
  urls:
    - http://apicurio:8080/apis/ccompat/v6

kafkaConnect:
  enabled: true
  clusters:
    - name: arcas-debezium
      url: http://debezium:8083

server:
  listenPort: 8080
